const products = [{"id": 1, "name": "Relic / браслеты", "category": "bracelets", "image": "assets/product-1.jpg"}, {"id": 2, "name": "Symbols / звенья", "category": "links", "image": "assets/product-2.jpg"}, {"id": 3, "name": "Nomination Angel / подвеска", "category": "links", "image": "assets/product-3.jpg"}, {"id": 4, "name": "Cross / кольцо", "category": "rings", "image": "assets/product-4.jpg"}, {"id": 5, "name": "Thorns / серьги", "category": "earrings", "image": "assets/product-5.jpg"}, {"id": 6, "name": "Signs / звенья", "category": "links", "image": "assets/product-6.jpg"}, {"id": 7, "name": "Wings / цепочка", "category": "necklaces", "image": "assets/product-7.jpg"}, {"id": 8, "name": "Black links / браслет", "category": "bracelets", "image": "assets/product-8.jpg"}, {"id": 9, "name": "Angel wings / серьги", "category": "earrings", "image": "assets/product-9.jpg"}, {"id": 10, "name": "Avelli / браслет", "category": "bracelets", "image": "assets/product-10.jpg"}, {"id": 11, "name": "Stars / браслет", "category": "bracelets", "image": "assets/product-11.jpg"}, {"id": 12, "name": "Millicent / браслет", "category": "bracelets", "image": "assets/product-12.jpg"}, {"id": 13, "name": "Liquid cross / серьги", "category": "earrings", "image": "assets/product-13.jpg"}, {"id": 14, "name": "Iron cross / кольцо", "category": "rings", "image": "assets/product-14.jpg"}, {"id": 15, "name": "Black cross / кольцо", "category": "rings", "image": "assets/product-15.jpg"}, {"id": 16, "name": "Blade / подвеска", "category": "necklaces", "image": "assets/product-16.jpg"}, {"id": 17, "name": "Angel / подвеска", "category": "necklaces", "image": "assets/product-17.jpg"}, {"id": 18, "name": "Collection / цепочки", "category": "necklaces", "image": "assets/product-18.jpg"}];const categoryNames={rings:'Кольца',bracelets:'Браслеты',links:'Звенья для браслетов',necklaces:'Подвески и цепочки',earrings:'Серьги'};
const descriptions={rings:'Выразительная форма для акцента на руках. Можно носить отдельно или сочетать с другими кольцами.',bracelets:'Украшение для запястья в альтернативной эстетике. Сочетай с кольцами и цепочками.',links:'Детали для персональной комбинации браслета. Совместимость и доступные варианты уточняются.',necklaces:'Акцент у линии шеи: символы, крылья и кресты для твоего образа.',earrings:'Деталь, которая обрамляет лицо и задаёт настроение всему образу.'};
const container=document.querySelector('#products'),dialog=document.querySelector('#product-dialog');let currentProduct;
function render(filter='all'){container.replaceChildren();products.filter(p=>filter==='all'||p.category===filter).forEach(p=>{const card=document.createElement('article');card.className='product';card.innerHTML=`<button data-product="${p.id}" aria-label="Посмотреть ${p.name}"><div class="product-image"><img loading="lazy" src="${p.image}" alt="${p.name}"><span aria-hidden="true">↗</span></div><h3>${p.name}</h3><p>${categoryNames[p.category]} · Подробнее ↗</p></button>`;container.append(card)})}render();
document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b))});render(b.dataset.filter)}));
document.addEventListener('click',e=>{const b=e.target.closest('[data-product]');if(!b)return;currentProduct=products.find(p=>p.id===Number(b.dataset.product));document.querySelector('#dialog-title').textContent=currentProduct.name;const img=document.querySelector('#dialog-image');img.src=currentProduct.image;img.alt=currentProduct.name;document.querySelector('#dialog-description').textContent=descriptions[currentProduct.category];dialog.showModal();document.body.style.overflow='hidden'});
dialog.querySelector('.close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});dialog.addEventListener('close',()=>document.body.style.overflow='');
const reduced=matchMedia('(prefers-reduced-motion: reduce)');function scrollToSection(target){target.scrollIntoView({behavior:reduced.matches?'instant':'smooth',block:'start'})}
document.querySelector('#ask-product').addEventListener('click',()=>{document.querySelector('#message').value=`Здравствуйте! Меня интересует ${currentProduct.name}. Подскажите стоимость и наличие.`;dialog.close();scrollToSection(document.querySelector('#contact'));document.querySelector('#message').focus({preventScroll:true})});
const menu=document.querySelector('.menu-toggle'),nav=document.querySelector('nav');menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));menu.textContent=open?'ЗАКРЫТЬ −':'МЕНЮ +'});
document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{const target=document.querySelector(a.getAttribute('href'));if(!target)return;e.preventDefault();scrollToSection(target);history.replaceState(null,'',a.getAttribute('href'));nav.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.textContent='МЕНЮ +'}));
const form=document.querySelector('#contact-form'),status=document.querySelector('#form-status'),download=document.querySelector('#download-message');
function validate(id){const field=document.getElementById(id);let error='';if(id==='consent'){if(!field.checked)error='Подтверди согласие на обработку данных.'}else if(!field.value.trim())error='Заполни это поле.';else if(id==='name'&&field.value.trim().length<2)error='Введи имя: минимум 2 символа.';else if(id==='email'&&field.validity.typeMismatch)error='Введи корректный email.';else if(id==='message'&&field.value.trim().length<10)error='Добавь подробности: минимум 10 символов.';document.getElementById(id+'-error').textContent=error;field.setAttribute('aria-invalid',String(!!error));field.setAttribute('aria-describedby',id+'-error');return !error}
form.addEventListener('submit',e=>{e.preventDefault();const ids=['name','email','message','consent'];const invalid=ids.filter(id=>!validate(id));download.hidden=true;if(invalid.length){status.textContent='Проверь отмеченные поля.';document.getElementById(invalid[0]).focus();return}status.textContent='Поля заполнены корректно. Сообщение не отправлено: получатель ещё не подключён. Можно скачать обращение.';download.hidden=false});form.addEventListener('input',e=>{if(e.target.id&&document.getElementById(e.target.id+'-error'))validate(e.target.id);download.hidden=true;status.textContent=''});
download.addEventListener('click',()=>{const text=`Обращение в Distortion\nИмя: ${form.elements.name.value.trim()}\nEmail: ${form.elements.email.value.trim()}\n\n${form.elements.message.value.trim()}`;const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='distortion-message.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)});
document.querySelector('#year').textContent=new Date().getFullYear();for(let i=0;i<24;i++){const s=document.createElement('span');s.className='falling-star';s.textContent=i%3?'✦':'✧';s.style.cssText=`left:${(i*43.7)%100}%;font-size:${10+i%5*5}px;animation-duration:${24+i%8*4}s;animation-delay:-${i*3.8}s;--rest:${i*17%100}vh`;document.querySelector('#stars').append(s)}
